version: '3.8'

services:
  client-nginx:
    build:
      context: ../client
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - server
    volumes:
      - ../client/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    environment:
      - NEXT_PUBLIC_API_URL=http://server:8080
    container_name: client_nginx_container

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    container_name: server_container

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: >
      bash -c "trap exit TERM; while :; do certbot certonly --webroot --webroot-path=/var/www/certbot -d travelspace.world -d www.travelspace.world -n --agree-tos --email rlagusrb619@gmail.com --no-eff-email --keep-until-expiring; sleep 12h & wait $${!}; done;"
