version: '3.8'

services:
  client-nginx:
    build:
      context: ../client
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - server
    volumes:
      - ../client/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NEXT_PUBLIC_API_URL=http://server:8080
    container_name: client_nginx_container

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    container_name: server_container
