version: '3.8'

services:
  postgres:
    image: postgres:13.5
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=traveler
      - POSTGRES_PASSWORD=traveler
      - POSTGRES_DB=TravleSpace
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
networks:
  app-network:
    driver: bridge

volumes:
  postgres:
