version: '3.8'

services:
  client-app:
    build:
      context: ../client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - server
    container_name: client_container

  client-nginx:
    build:
      context: ../client
      dockerfile: dockerfile.nginx
    ports:
      - '80:80'
    depends_on:
      - client-app
    volumes:
      - ../client/default.conf:/etc/nginx/conf.d/default.conf
    container_name: client_nginx_container

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    container_name: server_container
